public class Player{
   //write the class for a monopoly player
    private String name;
    private int money;
    private int position;
    private boolean inJail;
    private int jailTurns;
    private int numRailroads;
    private int numUtilities;
    private Street [] properties;
    private int numGetOutOfJailCards;
    private boolean isBankrupt;
    private int numTurns;
    private int numDoubles;
    private int numJailTurns;
    
    // private int numJailRolls;
    // private int numJailDoubles;
    // private int numJailCards;
    // private int numJailPaid;
    // private int numJailBids;
    // private int numJailBankrupts;
    // private int numJailRollsDoubles;
    // private int numJailRollsCards;
    // private int numJailRollsPaid;
    // private int numJailRollsBids;
    // private int numJailRollsBankrupts;
    // private int numJailCardsDoubles;
    // private int numJailCardsPaid;
    // private int numJailCardsBids;
    // private int numJailCardsBankrupts;
    // private int numJailPaidBids;
    // private int numJailPaidBankrupts;
    // private int numJailBidsBankrupts;
    // private int numJailRollsDoublesCards;
    // private int numJailRollsDoublesPaid;
    // private int numJailRollsDoublesBids;
    // private int numJailRollsDoublesBankrupts;
    // private int numJailRollsCardsPaid;
    // private int numJailRollsCardsBids;
    // private int numJailRollsCardsBankrupts;
    // private int numJailRollsPaidBids;
    // private int numJailRollsPaidBankrupts;
    // private int numJailRollsBidsBankrupts;
    // private int numJailCardsPaidBids;
    // private int numJailCardsPaidBankrupts;
    // private int numJailCardsBidsBankrupts;
    // private int numJailPaidBidsBankrupts;
    // private int numJailRollsDoublesCardsPaid;
    // private int numJailRollsDoublesCardsBids;
    // private int numJailRollsDoublesCardsBankrupts;
    // private int numJailRollsDoublesPaidBids;
    // private int numJailRollsDoublesPaidBankrupts;
    // private int numJailRollsDoublesBidsBankrupts;
    // private int numJailRollsCardsPaidBids;
    // private int numJailRollsCardsPaidBankrupts;
    // private int numJailRollsCardsBidsBankrupts;
    // private int numJailRollsPaidBidsBankrupts;
    // private int numJailCardsPaidBidsBankrupts;
    // private int numJailRollsDoublesCardsPaidBids;
    // private int numJailRollsDoublesCardsPaidBankrupts;
    // private int numJailRollsDoublesCardsBidsBankrupts;
    // private int numJailRollsDoublesPaidBidsBankrupts;
    // private int numJailRollsCardsPaidBidsBankrupts;
    // private int numJailRollsDoublesCardsPaidBidsBankrupts;
    // private int numJailRollsDoublesCardsPaidBidsBankrupts;
    // private int numJailRollsDoublesCardsPaidBidsBankrupts;
    // private int numJailRollsDoublesCardsPaidBidsBankrupts;
    // private int numJailRollsDoublesCardsPaidBidsBankrupts;
    // private int numJailRollsDoublesCardsPaidBidsBankrupts;
    // private int numJailRollsDoublesCardsPaidBidsBankrupts;
    // private int numJailRollsDoublesCardsPaidBidsBankrupts;
    // private int numJailRollsDoublesCardsPaidBidsBankrupts;
    
}